import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { SubscriptionProvider } from "@/providers/SubscriptionProvider";
import { getUserSubscription } from "@/actions/subscription/customer";
import { UserProvider } from "@/providers/UserProvider";
import { currentUser } from "@/lib/auth";
import { User } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Resume Matcher",
    template: "%s",
  },
  description: "Generated by Masoud",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const subscription = await getUserSubscription().catch(() => null);
  const user = await currentUser() as User;
   
  return (
    <html lang="en">
      <body className={"inter.className bg-slate-50"}>
        <NextTopLoader />
        <Toaster position="bottom-left" richColors theme="light" />
        <UserProvider initialUser={user}>
          <SubscriptionProvider initialSubscription={subscription}>
            {children}
          </SubscriptionProvider>
        </UserProvider>
      </body>
    </html>
  );
}
