import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Toaster } from '@/components/ui/sonner';
import NextTopLoader from 'nextjs-toploader';
import Head from 'next/head';
import { Montserrat } from 'next/font/google';
import clsx from 'clsx';

const montserrat = Montserrat({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Minova',
    template: '%s',
  },
  description: 'Generated by Masoud',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={clsx(montserrat.className, 'bg-slate-100')}>
        <NextTopLoader />
        <Toaster position="bottom-left" richColors theme="light" />
        {children}
      </body>
    </html>
  );
}
