import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
// import QueryProvider from "./QueryProvider";
import NextTopLoader from "nextjs-toploader";
import { SubscriptionProvider } from "@/providers/SubscriptionProvider";
import { Subscription } from "@prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Resume Matcher",
    template: "%s",
  },
  description: "Generated by Masoud",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        {/* <QueryProvider> */}
        <Toaster position="bottom-left" richColors theme="light" />

        <SubscriptionProvider subscription={{} as Subscription}>
          {children}
        </SubscriptionProvider>
        {/* <ReactQueryDevtools initialIsOpen={false} /> */}
        {/* </QueryProvider> */}
      </body>
    </html>
  );
}
