export const INDUSTRIES = [
  { value: 'software', label: 'Software Engineering' },
  { value: 'design', label: 'Design & Creative' },
  { value: 'marketing', label: 'Marketing & Advertising' },
  { value: 'finance', label: 'Finance & Accounting' },
  { value: 'healthcare', label: 'Healthcare & Medical' },
  { value: 'education', label: 'Education & Training' },
  { value: 'sales', label: 'Sales & Business Development' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'human-resources', label: 'Human Resources' },
  { value: 'construction', label: 'Construction & Skilled Trades' },
  { value: 'administration', label: 'Administrative & Office Support' },
];
export const CATEGORIES = {
  software: [
    {
      value: 'frontend-developer',
      label: 'Front-end Developer',
      caption: 'Crafts sleek, interactive user interfaces.',
      url: '/templates/software/frontend-developer.json',
    },
    {
      value: 'backend-developer',
      label: 'Back-end Developer',
      caption: 'Builds robust server-side logic and databases.',
      url: '/templates/software/backend-developer.json',
    },
    {
      value: 'fullstack-developer',
      label: 'Full-stack Developer',
      caption: 'Handles both front-end and back-end development.',
      url: '/templates/software/fullstack-developer.json',
    },
    {
      value: 'devops-engineer',
      label: 'DevOps Engineer',
      caption: 'Automates deployments and manages infrastructure.',
      url: '/templates/software/devops-engineer.json',
    },
    {
      value: 'software-engineer',
      label: 'Software Engineer',
      caption: 'Designs and develops scalable software systems.',
      url: '/templates/software/software-engineer.json',
    },
    {
      value: 'mobile-developer',
      label: 'Mobile App Developer',
      caption: 'Creates apps for iOS and Android platforms.',
      url: '/templates/software/mobile-developer.json',
    },
    {
      value: 'qa-engineer',
      label: 'QA / Test Engineer',
      caption: 'Ensures software quality through testing.',
      url: '/templates/software/qa-engineer.json',
    },
  ],
  design: [
    {
      value: 'graphic-designer',
      label: 'Graphic Designer',
      caption: 'Creates visuals for branding and marketing.',
      url: '/templates/design/graphic-designer.json',
    },
    {
      value: 'ui-designer',
      label: 'UI Designer',
      caption: 'Designs intuitive digital user interfaces.',
      url: '/templates/design/ui-designer.json',
    },
    {
      value: 'ux-designer',
      label: 'UX Designer',
      caption: 'Focuses on user experience and usability.',
      url: '/templates/design/ux-designer.json',
    },
    {
      value: 'product-designer',
      label: 'Product Designer',
      caption: 'Shapes the form and function of products.',
      url: '/templates/design/product-designer.json',
    },
    {
      value: 'web-designer',
      label: 'Web Designer',
      caption: 'Designs engaging and responsive websites.',
      url: '/templates/design/web-designer.json',
    },
  ],
  marketing: [
    {
      value: 'digital-marketer',
      label: 'Digital Marketer',
      caption: 'Drives online visibility and engagement.',
      url: '/templates/marketing/digital-marketer.json',
    },
    {
      value: 'seo-specialist',
      label: 'SEO Specialist',
      caption: 'Optimizes content to rank on search engines.',
      url: '/templates/marketing/seo-specialist.json',
    },
    {
      value: 'content-marketer',
      label: 'Content Marketer',
      caption: 'Creates valuable content to attract audiences.',
      url: '/templates/marketing/content-marketer.json',
    },
    {
      value: 'social-media-manager',
      label: 'Social Media Manager',
      caption: 'Manages and grows brand presence online.',
      url: '/templates/marketing/social-media-manager.json',
    },
    {
      value: 'marketing-manager',
      label: 'Marketing Manager',
      caption: 'Leads campaigns and marketing strategies.',
      url: '/templates/marketing/marketing-manager.json',
    },
  ],
  finance: [
    {
      value: 'accountant',
      label: 'Accountant',
      caption: 'Manages financial records and reporting.',
      url: '/templates/finance/accountant.json',
    },
    {
      value: 'financial-analyst',
      label: 'Financial Analyst',
      caption: 'Analyzes data to guide financial decisions.',
      url: '/templates/finance/financial-analyst.json',
    },
    {
      value: 'auditor',
      label: 'Auditor',
      caption: 'Reviews financial documents for accuracy.',
      url: '/templates/finance/auditor.json',
    },
    {
      value: 'bookkeeper',
      label: 'Bookkeeper',
      caption: 'Maintains accurate day-to-day financials.',
      url: '/templates/finance/bookkeeper.json',
    },
  ],
  healthcare: [
    {
      value: 'registered-nurse',
      label: 'Registered Nurse',
      caption: 'Provides direct patient care and support.',
      url: '/templates/healthcare/registered-nurse.json',
    },
    {
      value: 'medical-assistant',
      label: 'Medical Assistant',
      caption: 'Assists doctors with clinical and admin tasks.',
      url: '/templates/healthcare/medical-assistant.json',
    },
    {
      value: 'pharmacist',
      label: 'Pharmacist',
      caption: 'Dispenses medications and advises patients.',
      url: '/templates/healthcare/pharmacist.json',
    },
    {
      value: 'physical-therapist',
      label: 'Physical Therapist',
      caption: 'Helps patients recover mobility and function.',
      url: '/templates/healthcare/physical-therapist.json',
    },
  ],
  education: [
    {
      value: 'teacher',
      label: 'Teacher',
      caption: 'Educates students in a classroom setting.',
      url: '/templates/education/teacher.json',
    },
    {
      value: 'tutor',
      label: 'Tutor',
      caption: 'Provides personalized academic support.',
      url: '/templates/education/tutor.json',
    },
    {
      value: 'professor',
      label: 'Professor',
      caption: 'Teaches and researches at universities.',
      url: '/templates/education/professor.json',
    },
    {
      value: 'instructional-designer',
      label: 'Instructional Designer',
      caption: 'Designs effective learning experiences.',
      url: '/templates/education/instructional-designer.json',
    },
  ],
  sales: [
    {
      value: 'sales-representative',
      label: 'Sales Representative',
      caption: 'Connects with clients to drive product sales.',
      url: '/templates/sales/sales-representative.json',
    },
    {
      value: 'account-executive',
      label: 'Account Executive',
      caption: 'Manages client relationships and closes deals.',
      url: '/templates/sales/account-executive.json',
    },
    {
      value: 'business-development',
      label: 'Business Development',
      caption: 'Identifies and grows new business opportunities.',
      url: '/templates/sales/business-development.json',
    },
  ],
  'customer-service': [
    {
      value: 'customer-service-rep',
      label: 'Customer Service Representative',
      caption: 'Assists customers with inquiries and issues.',
      url: '/templates/customer-service/customer-service-rep.json',
    },
    {
      value: 'support-specialist',
      label: 'Support Specialist',
      caption: 'Resolves technical or product-related problems.',
      url: '/templates/customer-service/support-specialist.json',
    },
    {
      value: 'call-center-agent',
      label: 'Call Center Agent',
      caption: 'Handles customer calls and support tickets.',
      url: '/templates/customer-service/call-center-agent.json',
    },
  ],
  'human-resources': [
    {
      value: 'recruiter',
      label: 'Recruiter',
      caption: 'Finds and screens top job candidates.',
      url: '/templates/human-resources/recruiter.json',
    },
    {
      value: 'hr-manager',
      label: 'HR Manager',
      caption: 'Oversees employee relations and HR policies.',
      url: '/templates/human-resources/hr-manager.json',
    },
    {
      value: 'talent-acquisition',
      label: 'Talent Acquisition Specialist',
      caption: 'Focuses on attracting and hiring talent.',
      url: '/templates/human-resources/talent-acquisition.json',
    },
  ],
  construction: [
    {
      value: 'construction-worker',
      label: 'Construction Worker',
      caption: 'Performs physical labor on building sites.',
      url: '/templates/construction/construction-worker.json',
    },
    {
      value: 'electrician',
      label: 'Electrician',
      caption: 'Installs and maintains electrical systems.',
      url: '/templates/construction/electrician.json',
    },
    {
      value: 'plumber',
      label: 'Plumber',
      caption: 'Fixes and installs pipes and fixtures.',
      url: '/templates/construction/plumber.json',
    },
    {
      value: 'carpenter',
      label: 'Carpenter',
      caption: 'Builds and repairs wooden structures.',
      url: '/templates/construction/carpenter.json',
    },
  ],
  administration: [
    {
      value: 'administrative-assistant',
      label: 'Administrative Assistant',
      caption: 'Supports office tasks and scheduling.',
      url: '/templates/administration/administrative-assistant.json',
    },
    {
      value: 'office-manager',
      label: 'Office Manager',
      caption: 'Oversees daily operations of the office.',
      url: '/templates/administration/office-manager.json',
    },
    {
      value: 'executive-assistant',
      label: 'Executive Assistant',
      caption: 'Provides high-level admin support to execs.',
      url: '/templates/administration/executive-assistant.json',
    },
  ],
};
