export const SYSTEM_CONTEXT = `You are a helpful assistant for a resume building application.
  Your goal is to help users optimize their resumes for job applications.
  Always be precise, factual, and helpful.`;

export const Reasons = {
  GENERAL: 'GENERAL',
  CAREER_PROFILE_FROM_PDF: 'CAREER_PROFILE_FROM_PDF',
  JOB_SUMMARY: 'JOB_SUMMARY',
  CUSTOM_QUESTION: 'CUSTOM_QUESTION',
  RESUME_ANALYZE_EXPERIENCES: 'RESUME_ANALYZE_EXPERIENCES',
  RESUME_ANALYZE_SKILLS: 'RESUME_ANALYZE_SKILLS',
  SCORE_RESUME: 'SCORE_RESUME',
  MATCH_KEYWORDS_RESUME: 'MATCH_KEYWORDS_RESUME',
  SCORE_RESUME_EXPERIENCES: 'SCORE_RESUME_EXPERIENCES',
  SCORE_RESUME_PROJECTS: 'SCORE_RESUME_PROJECTS',
  ANALYZE_JOB_KEYWORDS: 'ANALYZE_JOB_KEYWORDS',
  EXTRACT_JOB_DESCRIPTION: 'EXTRACT_JOB_DESCRIPTION',
};

export type Reason = (typeof Reasons)[keyof typeof Reasons];
